# 公開するページのURL
baseURL = "https://sparrow-blue.github.io/blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "TEST"

theme = "terminal"
paginate = 20

# 自己紹介
[Author]
    name = "Kumazawa"
    bio = "Hello world!!"
    avatar = "img/avatar.JPG"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#2e8b57"

# SNS等のユーザー名
[Params.widgets.social]
  github = "sparrow-blue"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

[languages]
  [languages.ja]
    languageName = "English"
    title = "Test"
    subtitle = "test for terminal"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.ja.params.logo]
      logoText = "TEST LOGO"
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.ja.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"


[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'
