baseURL = "https://sparrow-blue.github.io/blog/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

theme = "terminal"
paginate = 20

[Author]
    name = "Kumazawa"
    bio = "Hello world!!"
    avatar = "img/avatar.JPG"

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = true
  fullWidthTheme = true
  centerTheme = false
  autoCover = true
  showLastUpdated = false
  # favicon = "favicon.ico"
  # updatedDatePrefix = "Updated"
  # oneHeadingSize = true # default
  # readingTime = false # default
  # Toc = false # default
  # TocTitle = "Table of Contents" # default

[languages]
  [languages.ja]
    languageName = "日本語"
    title = "Design and Implementation"
    subtitle = "Theory and Practice of Software Development"
    owner = "Kumazawa"
    keywords = ""
    copyright = ""
    menuMore = "もっと見る"
    readMore = "続き"
    readOtherPosts = "他の投稿を読む"
    newerPosts = "新しい投稿"
    olderPosts = "古い投稿"
    missingContentMessage = "ページが見つかりません"
    missingBackButtonLabel = "ホームに戻る"

  [languages.en]
    languageName = "English"
    title = "Design and Implementation"
    subtitle = "Theory and Practice of Software Development"
    owner = "Kumazawa"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Design and Implementation"
      logoHomeLink = "/blog/"

    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about/"

# [[module.imports]]
#   path = 'github.com/panr/hugo-theme-terminal'
