# 公開するページのURL
baseURL = "https://sparrow-blue.github.io/blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "TEST"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Kumazawa"
    bio = "Hello world!!"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#2e8b57"

# SNS等のユーザー名
[Params.widgets.social]
  github = "sparrow-blue"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

